[server]
Port = 8080

[service]
FilePath = "./Chillfactory.blk"
ValidMin = 5

[customize]
SideName = "Welcome"
HostAddress = ""
DownloadRouter = "/map"

[security]
RetryCount = 5
Password = "123123"
AdminPassword = "qweqwe"
AuthUA = true