[server]
Port = 8080
Https = false

[service]
MapDir = "./maps"
ValidMin = 5
UpdateCheck = true

[customize]
SideName = "Welcome"
HostAddress = ""
DownloadRouter = "/map"

[security]
RetryCount = 5
Password = "123123"
AdminPassword = "qweqwe"
AuthUA = false

[secret]
SecretKey = ""